default:
  tags:
    - docker

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules
    - .next

verify:
  image: cypress/browsers:node14.15.0-chrome86-ff82
  script:
    - yarn install --cache-folder .yarn
    - yarn lint
    - rm -rf cache/
    - yarn build
    - yarn cypress install
    - yarn run start &
    - yarn cypress run --browser chrome
